baseURL = 'https://docs.oss-rebuild.dev/'
languageCode = 'en-us'
title = 'OSS Rebuild'

[params]
  description = "OSS Rebuild"
  logo = "https://raw.githubusercontent.com/google/oss-rebuild/main/site/logo-dark.svg"
  github_project_url = "https://github.com/google/oss-rebuild"
  github_repo = "google/oss-rebuild"
  github_owner_url = "https://github.com/google"
  github_owner_name = "Google"

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "Trust"
  url = "/trust/"
  weight = 2

[[menus.main]]
  name = "Storage"
  url = "/storage/"
  weight = 3

[[menus.main]]
  name = "Builds"
  url = "/builds/"
  weight = 4

[[menus.main]]
  name = "Hosts"
  url = "/hosts/"
  weight = 5
